info:
  app:
    name: ${spring.application.name}

spring:
  application:
    name: Kafka Demo Consumer
  profiles:
    include:
      - kafka

logging:
  level:
    ROOT: WARN
    de.novatecgmbh.demo: info